// @ts-check
import {
  COLORS,
  SLOT_COUNT,
  PATTERN_TIME_START,
  COMBO_DECAY_S,
  PARTIAL_SERVE_EXTEND_S,
  SERVED_FLIGHT_S
} from './config.js';

/** @typedef {import('./types.js').ScoopColor} ScoopColor */
/** @typedef {import('./types.js').Customer} Customer */
/** @typedef {import('./types.js').Order} Order */
/** @typedef {import('./types.js').CustomerState} CustomerState */
/** @typedef {import('./types.js').WaveEventName} WaveEventName */
/** @typedef {import('./waves.js').Waves} Waves */

const ARRIVE_OFFSET = 150;   // px below the counter that customers slide in from
const SLIDE_Y_SPEED = 480;   // vertical slide speed (px/s)
const SLIDE_X_SPEED = 640;   // horizontal reposition speed when lanes shift
const BUBBLE_DELAY  = 0.5;   // beat before the speech bubble pops after arriving
export const REACH  = 120;   // how close the cone must be to serve a customer
const RESPAWN_DELAY = 0.35;  // beat before a freed slot is repopulated

export const STATE = Object.freeze({
  ARRIVING: 'arriving',
  DELAY:    'delay',
  WAITING:  'waiting',
  LEAVING:  'leaving'
});

/**
 * @param {number} cur
 * @param {number} target
 * @param {number} step
 */
function approach(cur, target, step) {
  if (Math.abs(target - cur) <= step) return target;
  return cur + Math.sign(target - cur) * step;
}

/**
 * The shop. 5 fixed slot positions; the active subset is driven by the Waves
 * director's phase (1, 2, 3, or 5 customers). Orders are generated by Waves
 * from a per-wave recipe pool, so order length is variable (1..5 scoops).
 *
 * Serving a customer reports the result to Waves and bubbles the resulting
 * progression event ('phaseUp' / 'waveUp' / null) back to the caller so the
 * game can fire gauge animations.
 */
export class Shop {
  /** @param {Waves} [waves] */
  constructor(waves) {
    this.waves = waves;
    /** @type {Customer[]} */
    this.customers = [];
    this.score = 0;
    this.combo = 0;
    this.comboTimer = 0;
    this.bestCombo = 0;
    this.orderTime = PATTERN_TIME_START;
    this.width = 0;
    this.respawnTimer = 0;
    this._id = 0;
    // When true the wave director's auto-spawn/reconcile is suspended so the
    // tutorial can stage a specific customer. Existing customers still animate.
    this.scripted = false;
  }

  reset() {
    this.customers = [];
    this.score = 0;
    this.combo = 0;
    this.comboTimer = 0;
    this.bestCombo = 0;
    this.respawnTimer = 0;
    this.scripted = false;
  }

  /**
   * Inject a customer with an explicit order at a chosen slot (tutorial use).
   * @param {number} slot
   * @param {ScoopColor[]} colors
   * @param {number} [value]
   * @param {number} [weight]
   * @returns {Customer}
   */
  spawnScripted(slot, colors, value = 180, weight = 1) {
    const x = this.slotX(slot);
    /** @type {Order} */
    const order = {
      recipe: colors.join('+'),
      colors: colors.slice(),
      originalColors: colors.slice(),
      served: [],
      value,
      weight,
      timeLeft: this.orderTime,
      duration: this.orderTime
    };
    /** @type {Customer} */
    const c = {
      id: this._id++, slot, x, targetX: x, yOff: ARRIVE_OFFSET,
      state: STATE.ARRIVING, timer: 0, waitT: 0, mood: null, order
    };
    this.customers.push(c);
    return c;
  }

  /** @param {number} width */
  layout(width) {
    this.width = width;
    for (const c of this.customers) c.targetX = this.slotX(c.slot);
  }

  /** @param {number} seconds */
  setOrderTime(seconds) { this.orderTime = seconds; }
  /** @param {ScoopColor} colorKey */
  hex(colorKey) { return COLORS[colorKey]; }
  get list() { return this.customers; }

  get comboFraction() {
    return COMBO_DECAY_S > 0 ? Math.max(0, this.comboTimer / COMBO_DECAY_S) : 0;
  }

  refreshCombo() {
    if (this.combo > 0) this.comboTimer = COMBO_DECAY_S;
  }

  /**
   * Wave-end cashout: read the live combo and reset it (the bar "breaks").
   * bestCombo is preserved — it was already banked on each serve.
   * @returns {number} the combo value at the moment of cashout
   */
  bankCombo() {
    const c = this.combo;
    this.combo = 0;
    this.comboTimer = 0;
    return c;
  }

  /** @param {number} n */
  addScore(n) { this.score += n; }

  /** @param {number} slot */
  slotX(slot) {
    return (slot + 0.5) / SLOT_COUNT * this.width;
  }

  _freeSlots() {
    const taken = new Set();
    for (const c of this.customers) {
      if (c.state !== STATE.LEAVING) taken.add(c.slot);
    }
    const free = [];
    for (let s = 0; s < SLOT_COUNT; s++) if (!taken.has(s)) free.push(s);
    return free;
  }

  /** Active (non-leaving) customer count. */
  _activeCount() {
    let n = 0;
    for (const c of this.customers) if (c.state !== STATE.LEAVING) n += 1;
    return n;
  }

  /** @param {number} slot */
  _spawn(slot) {
    const x = this.slotX(slot);
    const base = this.waves
      ? this.waves.pickOrder()
      : { recipe: 'pink', colors: /** @type {ScoopColor[]} */ (['pink']), value: 60, weight: 1 };
    /** @type {Order} */
    const order = {
      recipe: base.recipe,
      colors: base.colors.slice(),         // shrinks as the player partial-serves
      originalColors: base.colors.slice(), // snapshot for completion FX
      served: [],                          // grows with animated flying-scoop entries
      value: base.value,
      weight: base.weight,
      timeLeft: this.orderTime,
      duration: this.orderTime
    };
    this.customers.push({
      id: this._id++,
      slot,
      x,
      targetX: x,
      yOff: ARRIVE_OFFSET,
      state: STATE.ARRIVING,
      timer: 0,
      waitT: 0,
      mood: null,
      order
    });
  }

  /** Pick a random free slot and spawn a customer there. */
  _spawnRandom() {
    const free = this._freeSlots();
    if (free.length === 0) return;
    const slot = free[Math.floor(Math.random() * free.length)];
    this._spawn(slot);
  }

  /**
   * Advance animations, patience, and combo decay; reconcile customer count
   * against the current phase.
   * @param {number} dt
   * @param {{ patienceOn?: boolean }} [opts]
   * @returns {{ expired: number, comboLost: boolean }}
   */
  update(dt, { patienceOn = true } = {}) {
    const sx = SLIDE_X_SPEED * dt;
    const sy = SLIDE_Y_SPEED * dt;
    let expired = 0;
    let comboLost = false;
    /** @type {Customer[]} */
    const finishedLeaving = [];

    if (this.combo > 0 && this.comboTimer > 0) {
      this.comboTimer -= dt;
      if (this.comboTimer <= 0) {
        this.comboTimer = 0;
        this.combo = 0;
        comboLost = true;
      }
    }

    for (const c of this.customers) {
      c.x = approach(c.x, c.targetX, sx);

      // Tick each in-flight served scoop toward 1; landed scoops stop at 1.
      for (const s of c.order.served) {
        if (s.t < 1) s.t = Math.min(1, s.t + dt / SERVED_FLIGHT_S);
      }


      switch (c.state) {
        case STATE.ARRIVING:
          c.yOff = approach(c.yOff, 0, sy);
          if (c.yOff === 0) { c.state = STATE.DELAY; c.timer = BUBBLE_DELAY; }
          break;
        case STATE.DELAY:
          c.timer -= dt;
          if (c.timer <= 0) {
            c.state = STATE.WAITING;
            c.waitT = 0;
            c.order.timeLeft = c.order.duration;
          }
          break;
        case STATE.WAITING:
          c.waitT += dt;
          if (patienceOn) {
            c.order.timeLeft -= dt;
            if (c.order.timeLeft <= 0) {
              expired += 1;
              c.state = STATE.LEAVING;
              c.mood = 'angry';
            }
          }
          break;
        case STATE.LEAVING:
          c.yOff = approach(c.yOff, ARRIVE_OFFSET, sy);
          if (c.yOff === ARRIVE_OFFSET) finishedLeaving.push(c);
          break;
      }
    }

    for (const c of finishedLeaving) {
      const idx = this.customers.indexOf(c);
      if (idx >= 0) this.customers.splice(idx, 1);
    }

    if (expired > 0) { this.combo = 0; this.comboTimer = 0; }

    // Reconcile count to the current phase. During a wave celebration, push
    // everyone out; otherwise refill empty slots after a short beat. Suspended
    // while a scripted (tutorial) customer is staged.
    if (this.waves && !this.scripted) {
      if (this.waves.isCelebrating) {
        for (const c of this.customers) {
          if (c.state !== STATE.LEAVING) {
            c.state = STATE.LEAVING;
            c.mood = c.mood || 'happy';
          }
        }
        this.respawnTimer = RESPAWN_DELAY;
      } else {
        const want = this.waves.activeCount;
        const have = this._activeCount();
        if (have > want) {
          // Excess (e.g. just after a wave reset) — send extras off.
          let drop = have - want;
          for (const c of this.customers) {
            if (drop <= 0) break;
            if (c.state !== STATE.LEAVING) {
              c.state = STATE.LEAVING;
              c.mood = c.mood || 'happy';
              drop -= 1;
            }
          }
        } else if (have < want) {
          this.respawnTimer -= dt;
          if (this.respawnTimer <= 0) {
            this._spawnRandom();
            this.respawnTimer = RESPAWN_DELAY;
          }
        }
      }
    }

    return { expired, comboLost };
  }

  /**
   * Net colors waiting customers still need, after subtracting the player's
   * tray. Returned as a flat multi-set so a 3-pink order shows up as three
   * 'pink' entries. ScoopField uses this to bias incoming spawns toward
   * what's actually useful.
   * @param {ScoopColor[]} [trayColors]
   * @returns {ScoopColor[]}
   */
  demandColors(trayColors = []) {
    /** @type {ScoopColor[]} */
    const need = [];
    for (const c of this.customers) {
      if (c.state !== STATE.WAITING) continue;
      for (const k of c.order.colors) need.push(k);
    }
    // Single-pass subtraction: each tray scoop cancels at most one demand slot.
    for (const t of trayColors) {
      const i = need.indexOf(t);
      if (i >= 0) need.splice(i, 1);
    }
    return need;
  }

  /**
   * Index of the waiting customer the cone is standing at, or -1.
   * @param {number} coneX
   */
  customerAt(coneX) {
    let best = -1;
    let bestDist = REACH;
    for (let i = 0; i < this.customers.length; i++) {
      const c = this.customers[i];
      if (c.state !== STATE.WAITING) continue;
      const d = Math.abs(coneX - c.x);
      if (d < bestDist) { bestDist = d; best = i; }
    }
    return best;
  }

  /**
   * Would pressing ↑ here do something useful right now? Top-down delivery:
   * the customer takes the *top* tray scoop if its color is in their
   * remaining order (or rainbow is active). Drives the green-bubble glow.
   * @param {number} index
   * @param {ScoopColor[]} trayColors bottom-to-top
   * @param {boolean} [rainbow]
   */
  canServe(index, trayColors, rainbow = false) {
    const c = this.customers[index];
    if (!c || c.state !== STATE.WAITING) return false;
    if (trayColors.length === 0) return false;
    if (rainbow) return c.order.colors.length > 0;
    const top = trayColors[trayColors.length - 1];
    return c.order.colors.includes(top);
  }

  /**
   * Hand one scoop (the top of the tray) to the customer. If accepted,
   * their remaining order shrinks by one slot and patience extends. When
   * the last slot fills, the order completes (combo + score + leaving).
   *
   * @param {number} index
   * @param {ScoopColor} topColor
   * @param {boolean} [rainbow] wildcard mode: any color fills the next slot
   * @returns {{ accepted: boolean, complete: boolean, gained?: number, colors?: ScoopColor[], event?: WaveEventName | null }}
   */
  serveOne(index, topColor, rainbow = false) {
    const c = this.customers[index];
    if (!c || c.state !== STATE.WAITING) return { accepted: false, complete: false };

    const matchIdx = rainbow
      ? (c.order.colors.length > 0 ? 0 : -1)
      : c.order.colors.indexOf(topColor);
    if (matchIdx < 0) return { accepted: false, complete: false };

    c.order.colors.splice(matchIdx, 1);

    if (c.order.colors.length > 0) {
      // Partial — buy patience back so long orders don't expire mid-service.
      c.order.timeLeft = Math.min(c.order.duration, c.order.timeLeft + PARTIAL_SERVE_EXTEND_S);
      return { accepted: true, complete: false };
    }

    // Last slot filled — complete the order. Combo weight is now baked into
    // the order itself by waves.pickOrder (from the recipe's group).
    this.combo += c.order.weight || 1;
    this.comboTimer = COMBO_DECAY_S;
    this.bestCombo = Math.max(this.bestCombo, this.combo);
    const gained = c.order.value * this.combo;
    this.score += gained;
    const colors = c.order.originalColors.slice();

    c.state = STATE.LEAVING;
    c.mood = 'happy';

    const event = this.waves ? this.waves.onServed(colors) : null;
    this.respawnTimer = RESPAWN_DELAY;

    return { accepted: true, complete: true, gained, colors, event };
  }
}
